export const ROTATION_LINES = [
  "Grow my business",
  "Increase conversions",
  "Build a stunning site",
  "Reduce drop-off",
  "Grow my online presence",
  "Modernize my brand",
  "Fix mobile UX",
  "Speed up my site",
  "Polish the UI",
  "Book more demos",
  "Refresh my visuals",
  "Tell a clearer story",
  "Improve accessibility",
  "Build more trust",
  "Make a great first impression",
  "Stand out from competitors",
  "Win repeat visitors",
  "Make my site memorable",
  "Create a better experience",
  "Turn visitors into customers",
  "Clarify my offer",
  "Improve navigation",
  "Simplify checkout",
  "Launch faster",
];

